# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparcamientos',
            name='distrito',
            field=models.TextField(default=''),
        ),
    ]
