# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0002_aparcamientos_distrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparcamientos',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='aparcamientos',
            old_name='phone',
            new_name='telefono',
        ),
    ]
