# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparcamientos', '0003_auto_20170509_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparcamientos',
            name='latitud',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aparcamientos',
            name='longitud',
            field=models.TextField(default=''),
        ),
    ]
